### ISSUE TITLE
License for bcrypt_pbkdf port?

### ISSUE THREAD

**Issue by arekinath** [devi/tmp#1]
Hi!

I was hoping to make use of the port you've done here of the OpenBSD `bcrypt_pbkdf` function, but I noticed that it has no licensing headers on it at the moment. I'm assuming since it's very much a 1:1 port of the code from OpenBSD that it's under the original licenses for `blowfish.c` and `bcrypt_pbkdf.c`. Would that be correct?

I was hoping to make it into a small npm module so that I can use it in node.js easily.

Thanks!

**Comment by devi** [comment]
Sorry for late reply, become off the grid most lately.
You are correct about the licensing, it's the same license with the original bcrypt_pbkdf.c

Regards
